# Generated by Django 5.0.2 on 2024-02-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
