# Generated by Django 5.0.2 on 2024-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttest",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
