# Generated by Django 5.0.2 on 2024-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttest',
            name='category',
            field=models.ManyToManyField(to='post.category'),
        ),
    ]
